### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by davmcgregor** [davmcgregor/commerce-product-listing#1]
- [x] Init react app and delete boilerplate code
- [x] Create components structure
    - [x] Header
        - [x] Search
        - [x] Filter
    - [x] ProductList
        - [x] ProductCard
- [x] Set up context API
- [x] Set up lifecycle method and fetch function to bring in data
- [x] Set up utils functions for search and filter + tests
- [x] Wire up filter - get some basic visibility on Product components
- [x] Wire up search - get some basic visibility on Product components
- [x] Create a container wrapper for App (padding in line with design)
- [x] Bring in image files
- [x] Style using grid with responsive breakpoints
- [x] Style ProductCards - make sure to include 'Sale' indicator
- [x] Ensure image car lines up with select filter
- [x] Refine CSS as much as possible - rounded cards, transition
- [x] Style header components
- [x] Write unit tests for all
- [x] Fix loading flicker (fixed with conditional rendering in ProductList)
- [x] Ensure search on each keystroke (fixed with conditional logic in context)
- [x] Ensure no console errors
- [x] Ensure accessibility/aria-labelling/semantic html
- [x] Tidy up README
- [x] Final check against AC
